language: node_js
node_js:
  - v10
  - v8
  - v6
before_script: npm i
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token cat ./coverage/lcov.info | coveralls

notifications:
  slack: leduong:8FHnajypcfOykiQS6Hn6QBB5
